# Generated by Django 5.2 on 2025-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Half-Day', 'Half-Day'), ('Full-Day', 'Full-Day')], default='Full-Day', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=20),
        ),
    ]
