# Generated by Django 5.2 on 2025-04-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('user', 'date', 'clock_in')},
        ),
    ]
