# Generated by Django 5.2 on 2025-04-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_leavereportemployee_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportemployee',
            name='date',
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
